<script setup lang="ts">
import { MockupScreenLmsProfessorPortal, MockupScreenHrisAnalytics, MockupScreenLmsManagementPortal, MockupScreenLmsStudentPortal, MockupScreenLmsParentsPortal, MockupScreenHrisLearning, MockupScreenHrisPerformance, MockupScreenHrisSelfService } from '#components'
import { useWindowScroll } from '@vueuse/core'

definePageMeta({
  layout: 'product',
})

const { y } = useWindowScroll()

const features = [
  {
    title: 'Anytime, Anywhere Access',
    description: 'Learners reach educational content on any device, with flexibility and convenience that keep learning continuous.',
    icon: 'i-lucide-mouse-pointer',
    orientation: 'vertical' as const
  },
  {
    title: 'Performance & Progress',
    description: 'Educators track learner development through grades, reports, and course or module submissions in real time.',
    icon: 'i-lucide-bar-chart-2',
    orientation: 'vertical' as const
  },
  {
    title: 'Personalized Multimedia',
    description: 'Multimedia-based, personalized experiences that adapt to each student’s needs and drive greater engagement.',
    icon: 'i-lucide-settings-2',
    orientation: 'vertical' as const
  },
  {
    title: 'AI-Powered Tutorials',
    description: 'Dynamic, individualized learning paths generated by AI for a more effective and impactful learning experience.',
    icon: 'i-lucide-sparkles',
    orientation: 'vertical' as const
  }
]

const stats = [
  { value: '2M+', label: 'Active Learners' },
  { value: '500+', label: 'Institutions' },
  { value: '99.9%', label: 'Uptime SLA' },
  { value: '85%', label: 'Higher Completion' },
]

const testimonials = [
  {
    quote: 'LearnCore revolutionized our corporate training. Onboarding time is cut in half, and employee engagement with compliance training is at an all-time high.',
    author: 'David Wright',
    role: 'Director of L&D, TechNova',
    initials: 'DW',
  },
  {
    quote: "Our university switched to LearnCore last year. The faculty loves the intuitive grading tools, and students appreciate the mobile-first design.",
    author: 'Elena Rostova',
    role: 'Dean of E-Learning, State University',
    initials: 'ER',
  },
  {
    quote: 'The analytics give us incredible insight into how students interact with the material. We can continuously improve our courses based on real data.',
    author: 'Michael Chang',
    role: 'Founder, CodeCamp Online',
    initials: 'MC',
  },
]

const plans = [
  {
    title: 'Basic',
    description: 'Perfect for independent instructors and small teams.',
    price: '$99',
    features: [
      'Up to 250 active learners',
      'Unlimited courses',
      'Basic analytics',
      'Email support',
    ],
  },
  {
    title: 'Pro',
    description: 'For growing organizations needing advanced features.',
    price: '$299',
    badge: 'Most Popular',
    highlight: true,
    features: [
      'Up to 1,000 active learners',
      'Everything in Basic',
      'Custom domains & branding',
      'Live classroom integrations',
      'Advanced reporting',
      'Priority support',
    ],
  },
  {
    title: 'Enterprise',
    description: 'Custom solutions for large universities and corporations.',
    price: 'Custom',
    features: [
      'Unlimited learners',
      'Everything in Pro',
      'Custom API integrations',
      'Dedicated success manager',
      'Single Sign-On (SSO)',
      'SLA guarantee',
    ],
  },
]

const heroLinks = [
  { label: 'Start Free Trial', to: '#pricing', icon: 'i-lucide-rocket', size: 'xl' as const },
  { label: 'Watch Demo', color: 'neutral' as const, variant: 'subtle' as const, trailingIcon: 'i-lucide-play-circle', size: 'xl' as const },
]

const ctaLinks = [
  { label: 'Get Started Today', icon: 'i-lucide-rocket', size: 'lg' as const },
  { label: 'Talk to Sales', color: 'neutral' as const, variant: 'subtle' as const, trailingIcon: 'i-lucide-phone', size: 'lg' as const },
]

const logoIcons = [
  { name: 'i-simple-icons-coursera', label: 'Coursera' },
  { name: 'i-simple-icons-udemy', label: 'Udemy' },
  { name: 'i-simple-icons-edx', label: 'edX' },
  { name: 'i-simple-icons-khanacademy', label: 'Khan Academy' },
  { name: 'i-simple-icons-skillshare', label: 'Skillshare' },
  { name: 'i-simple-icons-duolingo', label: 'Duolingo' },
]

const checklist = [
    'Anytime, anywhere access',
    'Live chat & notifications',
    'Self-paced learning'
]

const modules = [
    { title: 'Management', icon: 'i-lucide-check', to: '#employee-records' },
    { title: 'Student', icon: 'i-lucide-check', to: '#recruitment' },
    { title: 'AI Tutor', icon: 'i-lucide-check', to: '#payroll' },
    { title: 'Professor', icon: 'i-lucide-check', to: '#timekeeping' },
    { title: 'Parent', icon: 'i-lucide-check', to: '#reports' },
]

const hubModules = [
    { label: 'Management', icon: 'i-lucide-shield-check', to: '#employee-records' },
    { label: 'Student', icon: 'i-lucide-circle-user-round', to: '#recruitment' },
    { label: 'AI Tutor', icon: 'i-lucide-sparkles', to: '#payroll' },
    { label: 'Professor', icon: 'i-lucide-user-check', to: '#timekeeping' },
    { label: 'Parent', icon: 'i-lucide-heart-handshake', to: '#reports' },
]

const featureDetails = [
    {
        id: 'management-portal',
        title: 'Management Portal',
        description: 'Manage, store, and collect every piece of curriculum data.',
        features: [
            { description: 'A cloud database migrating Programs, Subjects, Teachers, Students, and Subject codes — accessible anytime.', icon: 'i-lucide-cloud-cog' },
            { description: 'Calendar, incoming events, school mission and vision flow through a shared newsfeed with live chat.', icon: 'i-lucide-rss' },
            { description: 'Dashboard for course, curriculum, subject, graduates, scholarships, plus full user and role management.', icon: 'i-lucide-chart-pie' },
        ],
        orientation: 'horizontal' as const,
        component: MockupScreenLmsManagementPortal
    },
    {
        id: 'professor-portal',
        title: 'Professor Portal',
        description: 'Concrete plans, consistent methods, a durable companion.',
        features: [
            { description: 'Migrate assigned classes, view class lists, class feed, and teaching class in one place.', icon: 'i-lucide-layout-dashboard' },
            { description: 'Create lessons and attach modules, PowerPoint, Excel, PDF, text and Word files (up to 20MB), plus quizzes filtered by topic.', icon: 'i-lucide-file-type-corner' },
            { description: 'Set attendance, grade masterlists, time limits and date ranges; upload questions via CSV and score work per student or in groups of 2–20.', icon: 'i-lucide-upload' },
        ],
        orientation: 'horizontal' as const,
        reverse: true,
        component: MockupScreenLmsProfessorPortal
    },
    {
        id: 'student-portal',
        title: 'Student Portal',
        description: 'A systematized tool built for successful online learning.',
        features: [
            { description: 'Summary tables for current, conducted, and missed activities, with results viewable right after or within 24 hours.', icon: 'i-lucide-list-checks' },
            { description: 'Download lesson attachments, take class attendance in the LMS, and auto-post the classes you’re enrolled in.', icon: 'i-lucide-cloud-upload' },
            { description: 'File drive, class feed, instructor evaluation, schedule calendar, scholarships, self-paced learning, and real-time notifications.', icon: 'i-lucide-folder' },
        ],
        orientation: 'horizontal' as const,
        component: MockupScreenLmsStudentPortal
    },
    {
        id: 'parents-portal',
        title: 'Parents Portal',
        description: 'Peace of mind and comfort for every family.',
        features: [
            { description: 'Link to a child’s account via QR code to monitor activities, progress, and attendance any time.', icon: 'i-lucide-sparkles' },
            { description: 'Access University details — phone, telephone, and address — with no maximum number of students to add.', icon: 'i-lucide-user-check' },
            { description: 'A dedicated dashboard, profile management, and chat; view the student’s username and ID, pay fees online, and review payment logs.', icon: 'i-lucide-book-open' },
        ],
        orientation: 'horizontal' as const,
        reverse: true,
        component: MockupScreenLmsParentsPortal
    }
]
</script>

<template>
  <!-- Hero -->
  <UPageHero
        orientation="horizontal" :ui="{
            root: 'relative overflow-hidden min-h-[calc(100vh-var(--ui-header-height))] pb-14 flex flex-col justify-center',
            container: 'max-w-full'
        }">
        <template #headline>
            <UBadge variant="subtle" :ui="{ base: 'pr-2.5 gap-2' }" class="rounded-full mb-4">
                <span class="relative flex size-2">
                    <span
                        class="absolute inline-flex h-full w-full animate-ping rounded-full bg-primary-400 opacity-75"></span>
                    <span class="relative inline-flex size-2 rounded-full bg-primary-500"></span>
                </span>
                Introducing LearnCore 2.0
            </UBadge>
        </template>
        <template #title>
            Digital Learning,<br>Reimagined.
        </template>
        <template #description>
          A cloud <strong>Learning Management System</strong> that lets learners access content anytime, anywhere — while educators track development through grades, reports, and submissions. Built by Centralized Cloud Computing International.
        </template>

        <template #top>
            <!-- Background image with true parallax -->
            <div class="absolute -inset-y-[25%] inset-x-0 -z-20 bg-cover bg-center bg-no-repeat will-change-transform"
                :style="{
                    backgroundImage: 'url(\'/Student_learning_on_tablet_2K_20261005122406.jpg\')',
                    transform: `translateY(${y * 0.4}px)`
                }" />
            <!-- Adaptive overlay -->
            <div class="absolute inset-0 -z-10 bg-white/80 dark:bg-black/80" />
        </template>

        <template #footer>
            <div class="flex flex-wrap gap-x-6 gap-y-3">
                <UButton v-for="(link, index) in heroLinks" :key="index" v-bind="link" />
            </div>

            <ul class="mt-6 sm:mt-12 flex flex-wrap gap-x-6 gap-y-2">
                <li v-for="item in checklist" :key="item" class="flex items-center gap-2 text-sm text-toned">
                    <UIcon name="i-lucide-check" class="size-4 text-primary shrink-0" />
                    {{ item }}
                </li>
            </ul>
        </template>

        <!-- Ticker at bottom of hero -->
        <div
            class="absolute bottom-0 inset-x-0 border-t border-default bg-white/50 dark:bg-neutral-900/50 backdrop-blur-md overflow-hidden flex py-4 z-10">
            <div class="flex whitespace-nowrap animate-ticker w-max hover:animation-paused">
                <div class="flex items-center gap-16 pr-16 shrink-0" v-for="i in 4" :key="`ticker-group-${i}`">
                    <NuxtLink v-for="mod in hubModules" :key="mod.label" :to="mod.to"
                        class="flex items-center gap-2 text-sm font-bold text-toned uppercase tracking-wider hover:text-primary transition-colors">
                        <UIcon :name="mod.icon" class="size-5 text-primary" />
                        {{ mod.label }}
                    </NuxtLink>
                </div>
            </div>
        </div>
    </UPageHero>

  <!-- Social proof -->
  <!-- <div class="border-y border-default bg-muted/50 py-10">
    <UContainer>
      <p class="text-center text-dimmed text-xs font-semibold uppercase tracking-widest mb-8">
        Trusted by leading educational organizations
      </p>
      <div class="flex flex-wrap items-center justify-center gap-x-12 gap-y-6">
        <UIcon
          v-for="logo in logoIcons"
          :key="logo.name"
          :name="logo.name"
          :aria-label="logo.label"
          class="size-7 text-muted"
        />
      </div>
    </UContainer>
  </div> -->

  <!-- Core features grid -->
  <UPageSection
    id="features"
    headline="Digital learning"
    title="A foundation for enhanced e-learning"
    description="As education digitalizes, our LMS gives students and academic professionals a structured, effective way to teach, learn, and grow."
    :features="features"
    :ui="{ features: 'sm:grid-cols-2 lg:grid-cols-4 gap-x-12 gap-y-10' }"
  />

  <!-- Modules Structure -->
  <UPageSection headline="The Platform" title="Five connected portals, one platform"
      description="LearnCore connects every seat at the table — administrators, faculty, students, and parents — inside a single cloud platform, layered with an AI tutor that personalizes the path for every learner."
      orientation="horizontal" :features="modules" :ui="{ features: 'grid grid-cols-2 gap-4' }">
      <HubDiagram center-label="LMS CORE" :nodes="hubModules" />
  </UPageSection>

  <!-- Feature details -->
  <UPageSection v-for="(feature, index) in featureDetails" :key="index" :id="feature.id" :title="feature.title"
      :description="feature.description" :features="feature.features.map(f => ({ ...f, ui: { leading: 'p-0' } }))"
      :orientation="feature.orientation" :reverse="feature.reverse" :ui="{
          description: 'text-primary',
      }">
      <component :is="feature.component" />
  </UPageSection>

  <!-- Feature detail: Course Builder -->
  <UPageSection
    title="Interactive Course Builder"
    description="Create rich, multimedia courses without any coding. Drag and drop video lectures, interactive quizzes, and downloadable resources to build learning paths that keep students engaged from start to finish."
    orientation="horizontal"
  >
    <MockupScreenLmsCourse />
  </UPageSection>

  <!-- Feature detail: Analytics -->
  <UPageSection
    title="Actionable Learning Insights"
    description="Go beyond basic completion rates. Our advanced analytics dashboard reveals how learners are interacting with your content, highlighting areas where they excel and where they need additional support."
    orientation="horizontal"
    reverse
  >
    <MockupScreenLmsAnalytics />
  </UPageSection>

  <!-- Stats banner -->
  <!-- <div class="bg-primary dark:bg-primary/50 py-20">
    <UContainer>
      <div class="grid grid-cols-2 md:grid-cols-4 gap-10 text-center">
        <div v-for="stat in stats" :key="stat.label">
          <p class="text-4xl lg:text-5xl font-extrabold text-white">{{ stat.value }}</p>
          <p class="text-white/70 mt-2 text-sm lg:text-base font-medium">{{ stat.label }}</p>
        </div>
      </div>
    </UContainer>
  </div> -->

  <!-- Testimonials -->
  <!-- <UPageSection
    id="testimonials"
    headline="Success Stories"
    title="Empowering educators everywhere"
    description="Hear from schools and businesses that have transformed their learning programs with LearnCore."
  >
    <UPageGrid>
      <UCard v-for="t in testimonials" :key="t.author">
        <div class="flex flex-col h-full">
          <div class="flex gap-0.5 mb-5">
            <UIcon v-for="i in 5" :key="i" name="i-lucide-star" class="size-4 text-warning" />
          </div>
          <p class="text-muted italic leading-relaxed flex-1">"{{ t.quote }}"</p>
          <div class="flex items-center gap-3 mt-6 pt-6 border-t border-default">
            <UAvatar :text="t.initials" size="md" color="primary" />
            <div>
              <p class="font-semibold text-highlighted text-sm">{{ t.author }}</p>
              <p class="text-dimmed text-xs">{{ t.role }}</p>
            </div>
          </div>
        </div>
      </UCard>
    </UPageGrid>
  </UPageSection> -->

  <!-- Pricing -->
  <!-- <div class="bg-muted/30">
    <UPageSection
      id="pricing"
      headline="Pricing"
      title="Simple, transparent pricing"
      description="Start small and scale up as your learning community grows. All plans include a 14-day free trial."
    >
      <UPricingPlans :plans="plans" />
    </UPageSection>
  </div> -->

  <!-- CTA -->
  <!-- <UPageCTA
    title="Ready to elevate your learning programs?"
    description="Join thousands of organizations using LearnCore to deliver better education and training."
    :links="ctaLinks"
  /> -->

  <!-- CTA -->
  <div class="relative bg-primary dark:bg-primary/50 py-10 overflow-hidden">
      <div class="cta-grid-texture" />
      <UPageCTA title="Ready to elevate your learning programs?"
          description="Join thousands of organizations using LearnCore to deliver better education and training."
          variant="naked" :links="ctaLinks" :ui="{
              title: 'text-white',
              description: 'text-white/60'
          }" />
  </div>
</template>

<style scoped>
@keyframes ticker {
    0% {
        transform: translateX(0);
    }

    100% {
        transform: translateX(-25%);
    }
}

.animate-ticker {
    animation: ticker 40s linear infinite;
}

.hover\:animation-paused:hover {
    animation-play-state: paused;
}

.cta-grid-texture {
    position: absolute;
    inset: 0;
    background-image:
        linear-gradient(to right, rgba(255, 255, 255, 0.07) 1px, transparent 1px),
        linear-gradient(to bottom, rgba(255, 255, 255, 0.07) 1px, transparent 1px);
    background-size: 40px 40px;
    pointer-events: none;
    -webkit-mask-image: radial-gradient(ellipse 160% 110% at 50% -5%, black 50%, transparent 75%);
    mask-image: radial-gradient(ellipse 160% 110% at 50% -5%, black 50%, transparent 75%);
}
</style>