<script setup lang="ts">
import type { TableColumn } from '@nuxt/ui'

definePageMeta({
  layout: 'dashboard',
  breadcrumb: 'Reports'
})

const reports = [
  { id: 1, name: 'Q3 2026 Board Report', type: 'Quarterly', generatedBy: 'System', date: '2026-08-01', format: 'PDF' },
  { id: 2, name: 'FY2026 HR Performance Summary', type: 'Annual', generatedBy: 'Admin', date: '2026-07-15', format: 'Excel' },
  { id: 3, name: 'Campus Enrollment Trend Report', type: 'Monthly', generatedBy: 'System', date: '2026-08-10', format: 'PDF' },
  { id: 4, name: 'IT Compliance Audit Report', type: 'Ad-Hoc', generatedBy: 'CIO', date: '2026-08-20', format: 'PDF' },
]

const columns: TableColumn<typeof reports[0]>[] = [
  { accessorKey: 'name', header: 'Report Name' },
  { accessorKey: 'type', header: 'Type' },
  { accessorKey: 'generatedBy', header: 'Generated By' },
  { accessorKey: 'date', header: 'Date' },
  { accessorKey: 'format', header: 'Format' },
  { id: 'actions', header: '' },
]
</script>

<template>
  <div class="space-y-6">
    <div class="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
      <div>
        <h1 class="text-2xl font-bold text-highlighted tracking-tight">Executive Reports</h1>
        <p class="text-muted mt-1">Access, generate, and schedule consolidated executive reports.</p>
      </div>
      <UButton icon="i-lucide-file-plus" color="primary">Generate Report</UButton>
    </div>

    <UCard :ui="{ body: 'p-0 sm:p-0' }">
      <template #header>
        <div class="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <UInput icon="i-lucide-search" placeholder="Search reports..." class="w-full sm:max-w-sm" />
          <USelect :items="['All Types', 'Quarterly', 'Annual', 'Monthly', 'Ad-Hoc']" class="w-full sm:w-40" />
        </div>
      </template>
      <UTable class="scrollbar" :data="reports" :columns="columns">
        <template #name-cell="{ row }">
          <span class="font-medium text-highlighted">{{ row.original.name }}</span>
        </template>
        <template #format-cell="{ row }">
          <UBadge :color="row.original.format === 'PDF' ? 'error' : 'success'" variant="subtle" size="sm">{{ row.original.format }}</UBadge>
        </template>
        <template #actions-cell>
          <div class="flex justify-end gap-2">
            <UButton color="neutral" variant="ghost" icon="i-lucide-download" />
            <UButton color="neutral" variant="ghost" icon="i-lucide-more-horizontal" />
          </div>
        </template>
      </UTable>
    </UCard>
  </div>
</template>
