<script setup lang="ts">
definePageMeta({ layout: 'dashboard' })

const search = ref('')
const selectedType = ref('All')
const selectedStatus = ref('All')

const types = ['All', 'Fitness Summary', 'CHED Compliance', 'Grade-Level', 'Corporate Wellness', 'Sports Performance']
const statuses = ['All', 'Ready', 'Generating', 'Scheduled', 'Draft']

const reports = ref([
  { id: 'RPT-001', title: 'Q2 2026 Fitness Assessment Summary', type: 'Fitness Summary', generatedBy: 'Coach R. Santos', period: 'Q2 2026', records: 1842, status: 'Ready', createdAt: 'Aug 26, 2026' },
  { id: 'RPT-002', title: 'SY 2025-2026 CHED PE Compliance Report', type: 'CHED Compliance', generatedBy: 'Admin', period: 'SY 2025-2026', records: 3842, status: 'Ready', createdAt: 'Aug 20, 2026' },
  { id: 'RPT-003', title: 'Grade 10 Mid-Year Performance Report', type: 'Grade-Level', generatedBy: 'Coach A. Dela Cruz', period: 'Q1-Q2 2026', records: 340, status: 'Ready', createdAt: 'Aug 15, 2026' },
  { id: 'RPT-004', title: 'Corporate Wellness Q2 Program Results', type: 'Corporate Wellness', generatedBy: 'HR Admin', period: 'Q2 2026', records: 3000, status: 'Ready', createdAt: 'Aug 10, 2026' },
  { id: 'RPT-005', title: 'Varsity Athletes Seasonal Report', type: 'Sports Performance', generatedBy: 'Coach M. Reyes', period: 'Aug 2026', records: 24, status: 'Generating', createdAt: 'Aug 26, 2026' },
  { id: 'RPT-006', title: 'Q3 2026 Fitness Assessment Summary', type: 'Fitness Summary', generatedBy: 'Admin', period: 'Q3 2026', records: 0, status: 'Scheduled', createdAt: 'Sep 30, 2026' },
  { id: 'RPT-007', title: 'Annual Fitness Trend Report 2025', type: 'Fitness Summary', generatedBy: 'Coach R. Santos', period: 'SY 2024-2025', records: 0, status: 'Draft', createdAt: 'Aug 1, 2026' },
])

const statusConfig: Record<string, string> = {
  Ready: 'bg-success/10 text-success',
  Generating: 'bg-info/10 text-info',
  Scheduled: 'bg-warning/10 text-warning',
  Draft: 'bg-muted text-muted',
}

const filtered = computed(() =>
  reports.value.filter(r => {
    const matchSearch = !search.value || r.title.toLowerCase().includes(search.value.toLowerCase()) || r.id.toLowerCase().includes(search.value.toLowerCase())
    const matchType = selectedType.value === 'All' || r.type === selectedType.value
    const matchStatus = selectedStatus.value === 'All' || r.status === selectedStatus.value
    return matchSearch && matchType && matchStatus
  })
)

const columns = [
  { accessorKey: 'report', header: 'Report' },
  { accessorKey: 'type', header: 'Type' },
  { accessorKey: 'generatedBy', header: 'Generated By' },
  { accessorKey: 'period', header: 'Period' },
  { accessorKey: 'records', header: 'Records' },
  { accessorKey: 'createdAt', header: 'Date' },
  { accessorKey: 'status', header: 'Status' },
  { id: 'actions' },
]

const showGenerateModal = ref(false)
const selectedReport = ref<typeof reports.value[0] | null>(null)
const showDetailModal = ref(false)

function viewReport(r: typeof reports.value[0]) {
  selectedReport.value = r
  showDetailModal.value = true
}
</script>

<template>
  <div class="space-y-6">
    <div class="flex items-center justify-between">
      <div>
        <h1 class="text-2xl font-bold text-highlighted">Reports</h1>
        <p class="text-muted text-sm mt-1">Generate and manage fitness assessment and compliance reports</p>
      </div>
      <UButton icon="i-lucide-file-plus" label="Generate Report" size="sm" @click="showGenerateModal = true" />
    </div>

    <UCard :ui="{ body: 'sm:p-4' }">
      <div class="flex flex-wrap gap-3 items-center">
        <UInput v-model="search" placeholder="Search reports…" icon="i-lucide-search" class="flex-1 min-w-48" />
        <USelect v-model="selectedType" :items="types" class="w-48" />
        <USelect v-model="selectedStatus" :items="statuses" class="w-36" />
        <span class="text-sm text-muted ml-auto">{{ filtered.length }} reports</span>
      </div>
    </UCard>

    <UCard :ui="{ body: 'p-0 sm:p-0' }">
      <div class="overflow-x-auto">
        <UTable
          :data="filtered"
          :columns="columns"
          class="scrollbar w-full text-sm"
          :ui="{
            th: 'text-left px-4 py-3.5 text-xs text-dimmed font-semibold uppercase tracking-wider',
            td: 'px-4 py-4',
            tr: 'hover:bg-muted/30 transition-colors cursor-pointer'
          }"
          @select="(e, row) => viewReport(row.original)"
        >
          <template #report-header><span class="px-1">Report</span></template>
          <template #report-cell="{ row }">
            <div class="px-1">
              <p class="font-medium text-highlighted">{{ row.original.title }}</p>
              <p class="text-xs text-dimmed">{{ row.original.id }}</p>
            </div>
          </template>
          <template #type-cell="{ row }">
            <UBadge :label="row.original.type" color="neutral" variant="subtle" size="sm" />
          </template>
          <template #generatedBy-cell="{ row }">
            <span class="text-muted">{{ row.original.generatedBy }}</span>
          </template>
          <template #period-cell="{ row }">
            <span class="text-muted">{{ row.original.period }}</span>
          </template>
          <template #records-cell="{ row }">
            <span class="font-medium text-highlighted">{{ row.original.records > 0 ? row.original.records.toLocaleString() : '—' }}</span>
          </template>
          <template #createdAt-cell="{ row }">
            <span class="text-muted text-xs">{{ row.original.createdAt }}</span>
          </template>
          <template #status-cell="{ row }">
            <span class="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-medium" :class="statusConfig[row.original.status]">
              {{ row.original.status }}
            </span>
          </template>
          <template #actions-cell="{ row }">
            <div @click.stop>
              <UDropdownMenu
                :items="[[
                  { label: 'View', icon: 'i-lucide-eye', onSelect: () => viewReport(row.original) },
                  { label: 'Download PDF', icon: 'i-lucide-download', disabled: row.original.status !== 'Ready' },
                  { label: 'Send via Email', icon: 'i-lucide-mail', disabled: row.original.status !== 'Ready' }
                ]]"
                :content="{ align: 'end', side: 'bottom', sideOffset: 8 }"
                size="sm"
              >
                <UButton icon="i-lucide-more-vertical" size="xs" color="neutral" variant="ghost" />
              </UDropdownMenu>
            </div>
          </template>
          <template #empty>
            <div class="py-16 flex flex-col items-center justify-center">
              <UEmpty icon="i-lucide-file-bar-chart" title="No reports found" description="Generate your first fitness or compliance report" />
            </div>
          </template>
        </UTable>
      </div>
    </UCard>

    <!-- Detail Modal -->
    <UModal v-model:open="showDetailModal" :title="selectedReport?.title || ''" :description="selectedReport?.type">
      <template #body>
        <div v-if="selectedReport" class="space-y-4 text-sm">
          <div class="grid grid-cols-2 gap-4">
            <div><p class="text-dimmed text-xs uppercase tracking-wide font-semibold mb-1">Report ID</p><p class="text-highlighted font-medium">{{ selectedReport.id }}</p></div>
            <div><p class="text-dimmed text-xs uppercase tracking-wide font-semibold mb-1">Generated By</p><p class="text-highlighted font-medium">{{ selectedReport.generatedBy }}</p></div>
            <div><p class="text-dimmed text-xs uppercase tracking-wide font-semibold mb-1">Period</p><p class="text-highlighted font-medium">{{ selectedReport.period }}</p></div>
            <div><p class="text-dimmed text-xs uppercase tracking-wide font-semibold mb-1">Total Records</p><p class="text-highlighted font-medium">{{ selectedReport.records > 0 ? selectedReport.records.toLocaleString() : '—' }}</p></div>
            <div><p class="text-dimmed text-xs uppercase tracking-wide font-semibold mb-1">Date</p><p class="text-highlighted font-medium">{{ selectedReport.createdAt }}</p></div>
            <div>
              <p class="text-dimmed text-xs uppercase tracking-wide font-semibold mb-1">Status</p>
              <span class="inline-flex items-center px-2.5 py-1 rounded-full text-xs font-medium" :class="statusConfig[selectedReport.status]">{{ selectedReport.status }}</span>
            </div>
          </div>
        </div>
      </template>
      <template #footer>
        <UButton label="Close" color="neutral" variant="outline" @click="showDetailModal = false; selectedReport = null" />
        <UButton label="Download PDF" icon="i-lucide-download" :disabled="selectedReport?.status !== 'Ready'" />
      </template>
    </UModal>

    <!-- Generate Report Modal -->
    <UModal v-model:open="showGenerateModal" title="Generate Report" description="Configure and create a new fitness or compliance report">
      <template #body>
        <div class="space-y-4">
          <UFormField label="Report Title"><UInput placeholder="e.g. Q3 2026 Fitness Summary" class="w-full" /></UFormField>
          <div class="grid grid-cols-2 gap-4">
            <UFormField label="Report Type"><USelect :items="types.slice(1)" class="w-full" /></UFormField>
            <UFormField label="Period"><UInput placeholder="e.g. Q3 2026" class="w-full" /></UFormField>
          </div>
          <div class="grid grid-cols-2 gap-4">
            <UFormField label="Grade Level (optional)"><USelect :items="['All Grades', 'Grade 7', 'Grade 8', 'Grade 9', 'Grade 10', 'Grade 11', 'Grade 12']" class="w-full" /></UFormField>
            <UFormField label="Format"><USelect :items="['PDF', 'Excel', 'CSV']" class="w-full" /></UFormField>
          </div>
        </div>
      </template>
      <template #footer>
        <UButton label="Cancel" color="neutral" variant="outline" @click="showGenerateModal = false" />
        <UButton label="Generate Report" icon="i-lucide-file-plus" @click="showGenerateModal = false" />
      </template>
    </UModal>
  </div>
</template>
